version: '3.2'
services:
  category:
    build:
      context: ./
      dockerfile: ./docker/DockerfileCategory
    ports:
      - "8888:8888"
    networks:
      local_dev_net:
        aliases:
          - category_service
    depends_on:
      - web-shop-db-image

  product:
    build:
      context: ./
      dockerfile: ./docker/DockerfileProduct
    ports:
      - "8080:8080"
    networks:
      local_dev_net:
          aliases:
              - product_service
    depends_on:
      - web-shop-db-image

  web-shop-db-image:
    build:
      context: ./
      dockerfile: ./docker/DockerfileMySQL
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./.data/log:/var/log/mysql"
      - "./.data/conf:/etc/mysql/conf.d"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_BIN_LOG: 0
    ports:
      - "3306:3306"
    networks:
        local_dev_net:
            aliases:
                - web-shop-db-image

networks:
  local_dev_net:
    driver: bridge
