version: '3.2'
services:
  legacy:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PRODUCT_URL=http://product:8081
      - CATEGORY_URL=http://category:8082
    networks:
      local_dev_net:
        aliases:
          - legacy
    depends_on:
      - category
      - product

  category:
    build:
      context: ./
      dockerfile: ./docker/DockerfileCategory
    ports:
      - "8082:8080"
    environment:
      DATABASE_URL: jdbc:mysql://web-shop-db-image:3306
      PRODUCT_URL: http://product:8081
      DATABASE_USERNAME: categoryuser
      DATABASE_PASSWORD: akj34k3jdjfk3435jd3
    networks:
      local_dev_net:
        aliases:
          - category
    depends_on:
      - web-shop-db-image

  product:
    build:
      context: ./
      dockerfile: ./docker/DockerfileProduct
    ports:
      - "8081:8080"
    environment:
      DATABASE_URL: jdbc:mysql://web-shop-db-image:3306
      CATEGORY_URL: http://category:8082
      DATABASE_USERNAME: productuser
      DATABASE_PASSWORD: dj2342kjdlkfjl2j234
    networks:
      local_dev_net:
          aliases:
              - product
    depends_on:
      - web-shop-db-image

  web-shop-db-image:
    build:
      context: ./
      dockerfile: ./docker/DockerfileMySQL
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./.data/log:/var/log/mysql"
      - "./.data/conf:/etc/mysql/conf.d"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_BIN_LOG: 0
    ports:
      - "3306:3306"
    networks:
        local_dev_net:
            aliases:
                - web-shop-db-image

networks:
  local_dev_net:
    driver: bridge
