apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration
data:
  database_url: "jdbc:mysql://web-shop-db-image:3306"
  product_url: "http://product:8081"
  category_url: "http://category:8082"

---

#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  labels:
#    run: apache
#  name: apache
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      run: apache
#  template:
#    metadata:
#      labels:
#        run: apache
#    spec:
#      containers:
#        - image: docker.io/fatorice/webshop-apache:latest
#          imagePullPolicy: Always
#          name: apache
#          ports:
#            - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: category
  name: category
spec:
  replicas: 3
  selector:
    matchLabels:
      run: category
      app: webshop-category
      version: 1.0.0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: category
        app: webshop-category
        version: 1.0.0
    spec:
      containers:
        - image: docker.io/fatorice/webshop-category-service:latest
          imagePullPolicy: Always
          name: category
          ports:
          - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: database_url
            - name: PRODUCT_URL
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: product_url
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: webshop
                  key: category_user
                  optional: false
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webshop
                  key: category_pw
                  optional: false

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: legacywebshop
  name: legacywebshop
spec:
  replicas: 1
  selector:
    matchLabels:
      run: legacywebshop
      app: webshop
      version: 1.0.0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: legacywebshop
        app: webshop
        version: 1.0.0
    spec:
      containers:
        - image: docker.io/fatorice/legacy-webshop:latest
          imagePullPolicy: Always
          name: legacywebshop
          ports:
            - containerPort: 8080
          env:
            - name: PRODUCT_URL
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: product_url
            - name: CATEGORY_URL
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: category_url

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: product
  name: product
spec:
  replicas: 3
  selector:
    matchLabels:
      run: product
      app: webshop-product
      version: 1.0.0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: product
        app: webshop-product
        version: 1.0.0
    spec:
      containers:
        - image: docker.io/fatorice/webshop-product-service:latest
          imagePullPolicy: Always
          name: product
          ports:
          - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: database_url
            - name: CATEGORY_URL
              valueFrom:
                configMapKeyRef:
                  name: configuration
                  key: category_url
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: webshop
                  key: product_user
                  optional: false
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webshop
                  key: product_pw
                  optional: false

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    run: web-shop-db-image
  name: web-shop-db-image
spec:
  replicas: 1
  serviceName: web-shop-db-image
  selector:
    matchLabels:
      run: web-shop-db-image
      app: webshop-db
      version: 1.0.0
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: web-shop-db-image
        app: webshop-db
        version: 1.0.0
    spec:
      containers:
        - image: docker.io/fatorice/webshop-mysql-db-image:latest
          name: web-shop-db-image
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: c8de110f37300a53a971749
          ports:
          - containerPort: 3306
          resources: {}
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: category
    app: webshop-category
  name: category
spec:
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8080
  selector:
    run: category
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: product
    app: webshop-product
  name: product
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8080
  selector:
    run: product
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: legacywebshop
    app: webshop-webshop
  name: legacywebshop
spec:
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8080
  selector:
    run: legacywebshop
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    run: web-shop-db-image
    app: webshop-db
  name: web-shop-db-image
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    run: web-shop-db-image

---
#
#apiVersion: v1
#kind: Service
#metadata:
#  creationTimestamp: null
#  labels:
#    run: apache
#  name: apache
#spec:
#  ports:
#    - port: 80
#      protocol: TCP
#      targetPort: 80
#  selector:
#    run: apache
#  type: LoadBalancer